Update matching.py
AlphaPose gives compatibility issue due to newer versions of NumPy, specifically np.float being deprecated.

Solution for the following AttributeError: module 'numpy' has no attribute 'float'.